### ISSUE TITLE
Citation Styles that should be cross-checked in the code

### ISSUE THREAD

**Issue by ThiloteE** [subhramit/jabref#11]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

This is a living issue. Can be edited and updated on the fly.
These are styles that differ between entry preview and cited in Libreoffice. I started at History of the Human Sciences and am working my way up the list.

- [ ] Histoire & Mesure (Français)
  ```
    Smith, Bill, Bob Jones, & Jeff Williams, “Title of the test entry,” BibTeX Journal, 2016, vol. 34, no. 3, pp. 45–67.
  ```
  the space after "vol."

- [ ] Histoire@Politique. Politique, culture, société (Français)
  ```
    Smith Bill, Jones Bob and Williams Jeff, “Title of the test entry,” BibTeX Journal, vol. 34, no. 3, July 2016, pp. 45–67.
  ```
  the space after "vol."

**Comment by subhramit** [comment]
Expected:
![image](https://github.com/user-attachments/assets/db65f748-aad1-4d4e-8664-ab616d4500c9)
![image](https://github.com/user-attachments/assets/40fe9fa2-a32d-45cb-98eb-b2e6c0708eea)
Got:
![image](https://github.com/user-attachments/assets/5580ea5b-b6a8-42a1-a42d-0033b132e87c)

Seems fine to me, there is a space expected after vol. in the input HTML as well. Could you confirm if this is what you were talking about?

**Comment by ThiloteE** [comment]
Yes, I know it looks similar to human eye, but try with copy and then ctrl + f. It doesn't match.

**Comment by subhramit** [comment]
> Yes, I know it looks similar to human eye, but try with copy and then ctrl + f. It doesn't match.

Oh, that has a different implication, actually.
Remember we were trying to copy the preview from the select styles dialog, and on pasting as plain text, the text changed?

It's probably a difference in how text is formatted and parsed when produced in an OO document vs in the Preview.

For instance, take a look at the Histoire@Politique (the second style you mentioned in the issue):
![image](https://github.com/user-attachments/assets/5e7d53ce-cb0b-4602-9119-1d71f3d8ae0d)
The one on the left is copy pasted from what's rendered in OO, the one on the right is copy pasted from the preview.
Diff checker suggests that there is some difference in the `entry," BibTeX` part, and not at the `vol. 34`.

My guess: When we copy paste entries from the preview, the format is not parsed the same way as it was being done in the preview (here, "*BibTeX*" was supposed to be in italics, as it appears in the preview, but on copy-paste, that's lost). 
If you copy to the OO doc as well, the italics go away:
![image](https://github.com/user-attachments/assets/376e1488-cb82-47a0-bb84-afd0db110913)
Above: Rendered by cite, below: copy-pasted from Preview.
Similarly, when I copy pasted both in diff-checker, both lost the italics formatting.

Another example: what's rendered as a normal space in the preview may be rendered as a non-breaking space (`&nbsp` in escaped HTML) in OO, hence even if they look same to the eye, ctrl+f won't be able to match them. It means that the preview generator's processor parsed `&nbsp` but converted/produced it as a normal space.

**Comment by ThiloteE** [comment]
Won't fix for now.

**Comment by subhramit** [comment]
Update: Not an issue from our side, we are rendering citations as per the specification format. Implications:
1. Ctrl+F won't always work with keyboard-typed special characters e.g. spaces (what we might be looking for may be a non-breaking space, which we rendered into the document correctly as per the specification).
2. We are unsure how Preview is rendered, and how it interprets the escaped HTML characters. This *may* cause disparity between the actual citation and the preview, although not to the human eye. (Issue with the preview viewer, not CSL4LibreOffice).
Ref. https://github.com/subhramit/jabref/issues/10

**Comment by subhramit** [comment]
I am closing this issue, as it is not a definite issue here.
Superseded by https://github.com/subhramit/jabref/issues/18 and https://github.com/subhramit/jabref/issues/13
