### ISSUE TITLE
Select current style when opening "Style selection"

### ISSUE THREAD

**Issue by koppor** [subhramit/jabref#15]
good that the current style is displayed:

![image](https://github.com/user-attachments/assets/01eca7c3-3bef-48ba-ae87-04be79d47e33)

Better: It should be selected in the list.

1. Select the tab (CSL or JStyle)
2. Select it in the list

**Comment by subhramit** [comment]
The "auto scroll to and select set style in the list" feature does exist for CSL Styles. Implemented and merged in PR - B https://github.com/JabRef/jabref/pull/11521
Would need to extend it to tab selection and JStyles. Noted.

**Comment by koppor** [comment]
Does not work for CSL

![grafik](https://github.com/user-attachments/assets/04cf7c64-4642-4841-8e32-a37ce5953436)

**Comment by subhramit** [comment]
> Does not work for CSL
> 
> ![grafik](https://private-user-images.githubusercontent.com/1366654/355725865-04cf7c64-4642-4841-8e32-a37ce5953436.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTk3MDUsIm5iZiI6MTcyMzAxOTQwNSwicGF0aCI6Ii8xMzY2NjU0LzM1NTcyNTg2NS0wNGNmN2M2NC00NjQyLTQ4NDEtOGUzMi1hMzdjZTU5NTM0MzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDdUMDgzMDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWI4ZjY2YzM2ZDc3ZjlmOWFhNmQ5ZGQxZGQzY2FkODA4ZWQ1ZThkMTE0NDRkNDhlMDc3ZjA0ZjNlNmM2YTk4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9hLNhUcH4w24CmHzT07JiDhoQ2gmUqK1BphyTzTRhvQ)

This is weird. Will check.

**Comment by koppor** [comment]
Hint: Restart JabRef.

Extracted: 

1. Start JabRef
2. Open "Chocolate.bib"
3. Open Style selection
4. Select CSL Styles
5. Select IEEE
6. Click OK
7. Close JabRef
1. Start JabRef
3. Open Style selection
4. See that nothing is selected.

**Comment by subhramit** [comment]
> Hint: Restart JabRef.
> 
> Extracted:
> 
> 1. Start JabRef
> 2. Open "Chocolate.bib"
> 3. Open Style selection
> 4. Select CSL Styles
> 5. Select IEEE
> 6. Click OK
> 7. Close JabRef
> 8. Start JabRef
> 9. Open Style selection
> 10. See that nothing is selected.

I want to check something. Can you tell me if it works when:
1. The scroll and select happens within a JabRef session (without restart, by just closing and opening the Select style dialog again)
2. Follow step 1-9 above again. Then close and open the select style dialog again. Is the style then highlighted?

**Comment by Siedlerchr** [comment]
Works fine on mac in latest PR from 

<img width="850" alt="grafik" src="https://github.com/user-attachments/assets/4ebb547e-38d2-4779-b471-1a09afd7c4e7">

**Comment by ThiloteE** [comment]
Works on my Windows 10 Machine ;-)

![image](https://github.com/user-attachments/assets/a24c40a3-9930-4d77-aa92-6bf123d1f4e3)

**Comment by ThiloteE** [comment]
Seems to be a Koppor only issue.

**Comment by koppor** [comment]
I will close and re-open if the issue happens again
