### ISSUE TITLE
Add support for alphanumeric styles

### ISSUE THREAD

**Issue by koppor** [subhramit/jabref#17]
Besides numbers and author names, there is the alphanumeric style.

Please add support for din-1502-alphanumeric.csl. (Background: https://forums.zotero.org/discussion/12239/style-request-lecture-notes-in-informatics-lni-from-the-germany-computer-science-society)

Examples for in text citations:

![image](https://github.com/user-attachments/assets/821db4ca-75ec-4a8f-bfa2-4b0f2ae3b673)

For the normal citations, just the brackets are used. [Ez10], ...

Examples taken from: https://github.com/gi-ev/biblatex-lni

**Comment by subhramit** [comment]
TODO: Issue to be filed upstream at Citeproc-java.
Returns blank/empty in-text citation for the style in context.

**Comment by Siedlerchr** [comment]
Add a unit test to check the behavior first: https://github.com/JabRef/jabref/blob/main/src/test/java/org/jabref/logic/citationstyle/CitationStyleGeneratorTest.java

**Comment by Siedlerchr** [comment]
Din stlye https://github.com/citation-style-language/styles/blob/df939b87950c9f22a98e7a8188bbeabbc307bb42/din-1505-2.csl

Add a test for this style

**Comment by subhramit** [comment]
> Add a unit test to check the behavior first: https://github.com/JabRef/jabref/blob/main/src/test/java/org/jabref/logic/citationstyle/CitationStyleGeneratorTest.java

I manually checked it by logging the returned output of `makeInText`
Will add the tests tho

**Comment by subhramit** [comment]
Added as a case in https://github.com/JabRef/jabref/pull/11577/commits/0aead544dad801e06ee1f9ade2fa84c0e23daa89

**Comment by subhramit** [comment]
Test will be added in PR-D.

**Comment by koppor** [comment]
> Added as a case in [JabRef@0aead54](https://github.com/JabRef/jabref/commit/0aead544dad801e06ee1f9ade2fa84c0e23daa89)

Code seems to be copied (and adapted) from somewhere. Please add a `{@link ..}` to the method where you copied it.

> ` public static String authorsAlpha`

Why this method name? I think, the name should be good in the context of CSLCitationOOAdapter. Why `public`(I would have thought, it is private).

**Comment by subhramit** [comment]
> > Added as a case in [JabRef@0aead54](https://github.com/JabRef/jabref/commit/0aead544dad801e06ee1f9ade2fa84c0e23daa89)
> 
> Code seems to be copied (and adapted) from somewhere. Please add a `{@link ..}` to the method where you copied it.

Was supposed to use the original `authorsAlpha` from the `BracketedPattern` class you suggested, but it kept max authors as 3, had all 4 digits of year, and appended a '+' if max authors are exceeded, and the name for a single author was truncated to 3 letters instead of 4.
Hence, I made a local version of it for CSL, instead of changing it directly as it was being used at other places. Is the link necessary in this case then?
> 
> > ` public static String authorsAlpha`
> 
> Why this method name? I think, the name should be good in the context of CSLCitationOOAdapter. Why `public`(I would have thought, it is private).

1. Method name - thought of keeping the same as the old one because the target functionality is same. But you are right, should change to something like CSLAuthorsExtractor or something. 2. Public nature - For easy testing later.

**Comment by koppor** [comment]
Discussion result (chat): One `authorsAlpha`, not variants. We are working on a common understanding at https://github.com/JabRef/jabref/pull/11614.
