### ISSUE TITLE
Smart space before

### ISSUE THREAD

**Issue by koppor** [subhramit/jabref#19]
Note: I call the action to insert a citation in the form `[1]` ACTiON, since the buttons are currently wrong. See. https://github.com/subhramit/jabref/issues/13.

1. User types spaces
2. User triggers ACTION
3. `[1]` should be inserted. (With `1` being a representative of the "right" number)

Actual result: ` [1]` inserted.

I know, I asked for "space before". I did not unzip.

If it is not possible to check if a space is before the cursor and handle accordingly, please do not insert any space.

**Comment by subhramit** [comment]
Okay, tricky one. I will remove the proceeding space and keep this issue open if we figure out that there is a smart way to do this.

**Comment by subhramit** [comment]
> Okay, tricky one. I will remove the proceeding space and keep this issue open if we figure out that there is a smart way to do this.

Scratch that, there was.
Implemented smart spaces till 1 extra space :)

**Comment by koppor** [comment]
I checked. Thank you!

I improved it to NOT insert a space after. Reason: Typically, a citation ends a sentence. Deletion of a character is more work.
