### ISSUE TITLE
Select current selected style tab (!)

### ISSUE THREAD

**Issue by koppor** [subhramit/jabref#24]
My JabRef after startup:

![image](https://github.com/user-attachments/assets/4d526b86-3825-4de9-b75f-dddad6ddb31d)

It should look like:

![image](https://github.com/user-attachments/assets/8b5f559b-c7f8-4894-be67-e8289d2c3f73)

I think, only the tab switching is missing!

**Comment by subhramit** [comment]
Added auto select tab feature based on last used style from preferences

**Comment by koppor** [comment]
You can link issues from commits by adding the full (!) issue URL to your commit message. That supports quick reviewing of changes.

**Comment by subhramit** [comment]
> You can link issues from commits by adding the full (!) issue URL to your commit message. That supports quick reviewing of changes.

Oh, didn't know this. Could you clarify if I have to add an exclamation mark to the issue title like on this one? Or the commit message? Or just append the url in the commit message?

**Comment by koppor** [comment]
I needed to select another style, then it worked.
