### ISSUE TITLE
Make Settings > Sync bibliography work with CSL

### ISSUE THREAD

**Issue by ThiloteE** [subhramit/jabref#26]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 10, commit 1534516a2651e107743076975fd948071a46fbdd

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

The setting "Automatically sync bibliography when inserting a citation" does not yet yield any noticeable difference.
Should be similar betwen main (1534516a2651e107743076975fd948071a46fbdd) and in PR commit cd2539c3aa734ab8459d5800418a53532b4245ef

![image](https://github.com/user-attachments/assets/0fc02fdb-ad82-47cf-a9e1-9a93ec6b5b12)

### Expected outcome:
Inserting a citation will refresh the bibliography. For example, choosing a different citation style should update all existing entries in the bibliography and display them in the new style.

Very similar, but slightly different issue: https://github.com/subhramit/jabref/issues/22

### Complications

What happens, if users want to have various citation styles in one document? Various bibliographies?
Should all be bibliographies be updated?

**Comment by subhramit** [comment]
Current behavior: reference marks are inserted (and a counter is maintained) independent of the style chosen for the in-text (or non-bibliographic) citations (\citet and \cite).
When "Make bibliography" is triggered, only one bibliography section is generated/refreshed based on the existing reference marks and **currently selected CSL style**.

**Comment by subhramit** [comment]
As per my investigation, this feature does not work with JStyle either, and not because of any change made during the CSL project (tested using JabRef 5.13 stable).
We'll have to look a bit deeper to fix it, and then extend it for CSL.

**Comment by subhramit** [comment]
Updated behavior: JStyle and CSL now behave independently of each other, and are linked to individual bibliography sections if used together. This is due to difference in annotation used for the text sections.
