### ISSUE TITLE
[Preview and cite differs] Modern Language Association 9th

### ISSUE THREAD

**Issue by ThiloteE** [subhramit/jabref#9]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 10, JabRef commit 58a3bfe7811acc6ab9c4c2040d04961eb9417ebe

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

![image](https://github.com/user-attachments/assets/a7e04212-b594-4358-bcef-586cc0c2957f)

**Comment by ThiloteE** [comment]
For some reason, the style constantly falls back to IEEE, even though I have selected Modern Language Association 9th multiple times.

**Comment by Siedlerchr** [comment]
@ThiloteE  did you update your submodules?

**Comment by ThiloteE** [comment]
Ah, I am embarassed. I forgot that "choose style" does not automatically sync (yet) with the style that is chosen in the preferences. My bad. This is a no issue. I fixed it by choosing the correct style in the JabRef preferences for the preview tab.
